queues:
  - name: "HighPriorityQueue"
    durability: "disk"
    order: "fifo"
    message_ttl: 300

  - name: "LogsQueue"
    durability: "memory"
    order: "none"
    message_ttl: 60

  - name: "EventsQueue"
    durability: "disk"
    order: "fifo"
    message_ttl: 0

  - name: "TempQueue"
    durability: "memory"
    order: "none"
    message_ttl: 10

  - name: "test_queue"
    durability: "disk"
    order: "fifo"
    message_ttl: 10 